# -*- coding: utf-8 -*-
"""HSBC_prueba_tecnica

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16me-t4eyYJIM3YVgjn_bmQxLb_DBW9Te

# Income prediction model
**Objetive:** Develop a predictive model to determine if a given person* will be over the 50k threshold.

*data entry
"""

!pip install phik

# Loading packages
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score, roc_curve
from sklearn.metrics import accuracy_score, precision_score
import phik
from phik.report import plot_correlation_matrix
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

# Loading the dataset
# This lets me upload the file i choose from my libraries
from google.colab import files
import io
archivo_subido = files.upload()
nombre_archivo = next(iter(archivo_subido))

# Cleaning data

df_data = pd.read_excel(io.BytesIO(archivo_subido[nombre_archivo]), sheet_name='Dataset')
df_data.columns = df_data.columns.str.strip().str.lower().str.replace(' ', '_')
df_data = df_data.rename(columns={
    'ocupation': 'occupation',
    'ocupation.1': 'occupation_id',
    'ernings_flag': 'earnings_flag',
    'ernings_flag.1': 'earnings_flag_id'
})
columnas_id = [col for col in df_data.columns if col.endswith('.1')]
df_data_explor = df_data.drop(columns=columnas_id).copy()
df_data_explor.replace('?', np.nan, inplace=True)

# cantidad de valores nulos
print("Null values (column):")
print(df_data_explor.isnull().sum())

columnas_categoricas = df_data_explor.select_dtypes(include=['object']).columns
for col in columnas_categoricas:
    df_data_explor[col] = df_data_explor[col].astype('category')

print("\nClean dataframe info:")
#df_data_explor.info()
df_data_explor.head()

"""In this code block we changed some of the names of the variables, making them standard. We observe how many individual data cells are missing, preparing our data transformation choices for later. (Trating nulls as 0, as a median or other cases)

## Exploratory/Descriptive Analysis (EDA)
During the dataset exploration, the following key findings were identified:
* **Class Imbalance:** The vast majority of records belong to the `<=50K` class, which requires weight balancing techniques during training.
* ** Possible multicollinearity:** somewhat significant correlation (noise) was detected between demographic variables such as `marital_status` and `type_of_relationship` (Phi_K > 0.68). As well as `Sex` and `Type of relationship` (Phi_K > 0.84).
* **Skewed Distribution:** Financial variables like `capital_gain` and `capital_loss` are heavily skewed towards zero but contain high predictive power for the minority class.
"""

# fnlwgt = 'number of units in the target population'
# How many people are represented with a given variable of the dataset
# Total fnlwgt
print(f"Sum Final Weight: {df_data_explor['fnlwgt'].sum():,}\n")

# We will use "earnings_flag_id" for our initial calculations (binary variable) (1 = >50K, 0 = <=50K)
menor_50k = (df_data_explor['earnings_flag_id'] == 0).sum()
mayor_50k = (df_data_explor['earnings_flag_id'] == 1).sum()
total_personas = menor_50k + mayor_50k

print(f"Total de personas (filas en dataset): {total_personas:,}")
print(f" # ingresos >50k: {mayor_50k:,}")
print(f" # ingresos <=50k: {menor_50k:,}")
print(f"Porcentaje # con ingresos >50k: {mayor_50k / total_personas * 100:.2f}%\n")


cols_categoricas = [
    'type_of_work',
    'education_level',
    'marital_status',
    'type_of_relationship',
    'sex',
    'native_country'
]
print("")
print("PORCENTAJE DE PERSONAS QUE GANAN >50K POR CATEGORÍA")
for col in cols_categoricas:
    stats = df_data_explor.groupby(col)['earnings_flag_id'].mean().sort_values(ascending=False) * 100
    stats = stats.dropna()

    print(f"Variable: {col.replace('_', ' ').upper()}")
    print(stats.head(10)) # Top 10
    print("-" * 40)


cols_numericas = ['age_of_client', 'hours_of_work_per_week']
sns.set_theme(style="whitegrid")

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

for i, col in enumerate(cols_numericas):
    sns.histplot(
        data=df_data_explor,
        x=col,
        hue='earnings_flag',
        multiple="stack",
        palette="magma",
        bins=25,
        ax=axes[i]
    )

    # Format
    titulo = col.replace('_', ' ').title()
    axes[i].set_title(f'Distribución de {titulo} por Nivel de Ingreso', fontsize=14)
    axes[i].set_xlabel(titulo, fontsize=12)
    axes[i].set_ylabel('Frecuencia (Cantidad de Personas)', fontsize=12)

# Layout adjustment
plt.tight_layout()
plt.show()

"""The initial EDA section above only reveals information about the income with single variables. We use this to understand/see how skewed the data can be towards one group or other self contained in a single variable analysis. This will help us to build a weighted method to avoid skewing the results for the model.

#Multiple variable EDA (correlations)
"""

# Choosing numerical variables for correlation analysis

cols_numericas_reales = [
    'age_of_client',
    'hours_of_work_per_week',
    'capital_gain',
    'capital_loss',
    'earnings_flag_id' # 0 o 1
]

# Matrix
matriz_corr = df_data_explor[cols_numericas_reales].corr()
plt.figure(figsize=(10, 8))

# We only care about half of the matrix
mask = np.triu(np.ones_like(matriz_corr, dtype=bool))
sns.heatmap(
    matriz_corr,
    mask=mask,
    annot=True,
    fmt=".2f",
    cmap='coolwarm', # azul (negativo), rojo (positivo)
    vmin=-1, vmax=1,
    linewidths=0.5,
    cbar_kws={"shrink": .8}
)

plt.title('Matriz de Correlación de Pearson\n(Solo Variables Continuas y Target)', fontsize=14)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""The numerical variables do not have enough information between them to tell the full story, we will need to look into the categorical variables next."""

# Full matrix calculation
columnas_interes = [
    'age_of_client',
    'hours_of_work_per_week',
    'type_of_work',
    'education_level',
    'marital_status',
    'occupation',
    'type_of_relationship',
    'sex',
    'native_country',
    'earnings_flag_id' # Target
]

df_phik = df_data_explor[columnas_interes].copy()

matriz_phik = df_phik.phik_matrix()
plt.figure(figsize=(12, 10))

sns.heatmap(
    matriz_phik,
    annot=True,
    fmt=".2f",           # ceiling
    cmap='Blues',
    vmin=0, vmax=1,      # PhiK strict rank
    linewidths=0.5,
    cbar_kws={"shrink": .8}
)

plt.title('Correlation matrix (Global) (Phi_K)\nCategorical, numeric and target variables', fontsize=16)
plt.xticks(rotation=45, ha='right', fontsize=11)
plt.yticks(fontsize=11)
plt.tight_layout()
plt.show()

print("\n--- Income ranking ---")
print("Variable correlation with 'earnings_flag_id' (high to low):")

# We need the target column, to understand each variables relationship with income above or below 50k
ranking_target = matriz_phik['earnings_flag_id'].sort_values(ascending=False).drop('earnings_flag_id')
print(ranking_target)

"""## Methodology Selection
Several classification methodologies were evaluated:
1. **Logistic Regression:** (Pros: High interpretability. Cons: Fails with non-linear relationships and multicollinearity).
2. **Discriminant Analysis (LDA/QDA):** (Pros: Uses Mahalanobis distances. Cons: Collapses with sparse matrices from One-Hot Encoding).
3. **Support Vector Machines (SVM):** (Pros: Robust in high dimensionality. Cons: Prohibitive computational cost for large samples).
4. **Gradient Boosting (XGBoost):** (Pros: Maximum predictive performance. Cons: Higher tendency to overfit if not tuned correctly).
5. **Random Forest:** (Pros: Immune to scale, handles skewed variables. Cons: acts like a blackbox and during training can learn the dataset perfectly, skewing real life data in production).

**Final Selection:** **Random Forest** was chosen. This methodology allows us to isolate the noise from transformed categorical variables, process the skewness of financial variables without standardization, and solve the computational bottleneck by parallelizing the creation of multiple decision trees.
"""

# Logistical regression

cols_features = [
    'age_of_client',
    'hours_of_work_per_week',
    'education_level',
    'marital_status',
    'type_of_relationship'
]

X = df_data_explor[cols_features].copy()
y = df_data_explor['earnings_flag_id'] # 1 (>50k) y 0 (<=50k)

# Median values for nulls
X['age_of_client'] = X['age_of_client'].fillna(X['age_of_client'].median())
X['hours_of_work_per_week'] = X['hours_of_work_per_week'].fillna(X['hours_of_work_per_week'].median())

# Variable Dummy / One-Hot Encoding
X_encoded = pd.get_dummies(X, drop_first=True)


# stratify=y for class imbalance
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42, stratify=y
)

# Scaling numerical values for preformance

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#Training
modelo_logistico = LogisticRegression(max_iter=1000, random_state=42)
modelo_logistico.fit(X_train_scaled, y_train)

# El modelo predice la clase final (0 o 1) basado en el umbral > 0.5
y_pred = modelo_logistico.predict(X_test_scaled)

y_prob = modelo_logistico.predict_proba(X_test_scaled)[:, 1]

# Preformance metrics
print("--- CLASSIFICATION REPORT ---")
print(classification_report(y_test, y_pred))

print(f"ROC AUC Score: {roc_auc_score(y_test, y_prob):.4f}\n")

# Confussion Matrix and ROC Curve
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[0], cbar=False)
axes[0].set_title('Confusion Matrix')
axes[0].set_xlabel('Predicted Label')
axes[0].set_ylabel('Actual Label')
axes[0].set_xticklabels(['<=50K (0)', '>50K (1)'])
axes[0].set_yticklabels(['<=50K (0)', '>50K (1)'])

# ROC
fpr, tpr, umbrales = roc_curve(y_test, y_prob)
axes[1].plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC Curve (AUC = {roc_auc_score(y_test, y_prob):.2f})')
axes[1].plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
axes[1].set_xlim([0.0, 1.0])
axes[1].set_ylim([0.0, 1.05])
axes[1].set_xlabel('False Positive Rate (FPR)')
axes[1].set_ylabel('True Positive Rate (TPR)')
axes[1].set_title('ROC Curve')
axes[1].legend(loc="lower right")

plt.tight_layout()
plt.show()

"""## Random forests (using capital gains)

#Assumptions Made
1. **Missing at Random:** It was assumed that missing values in age and hours worked were random, imputing them with the spatial median.
2. **Financial Zeros:** It was assumed that missing data in `capital_gain` and `capital_loss` equals a value of $0.
3. **Sample Independence:** It is assumed that each row represents an independent individual and that the training subset (80%) is a faithful representation of the total universe.
4. **Cost of Error:** It is assumed that the business cost of a False Negative (ignoring a >50K client) is greater than that of a False Positive, justifying the use of balanced class weights.
"""

# Random forests columns

cols_finales = [
    'age_of_client',
    'hours_of_work_per_week',
    'education_level',
    'occupation',
    'type_of_relationship',
    'capital_gain',
    'capital_loss'
]

X = df_data_explor[cols_finales].copy()
y = df_data_explor['earnings_flag_id']

# Imputing nulls
X['age_of_client'] = X['age_of_client'].fillna(X['age_of_client'].median())
X['hours_of_work_per_week'] = X['hours_of_work_per_week'].fillna(X['hours_of_work_per_week'].median())
X['capital_gain'] = X['capital_gain'].fillna(0)
X['capital_loss'] = X['capital_loss'].fillna(0)

# One-Hot Encoding
X_encoded = pd.get_dummies(X, drop_first=True)

# Stratified Split (80/20)
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42, stratify=y
)


# MODEL TRAINING (RANDOM FOREST)

print("Training Optimized Random Forest...")

modelo_rf_final = RandomForestClassifier(
    n_estimators=200,
    class_weight='balanced',
    max_depth=15,
    n_jobs=-1,
    random_state=42
)

modelo_rf_final.fit(X_train, y_train)


# PREDICTIONS, METRICS & UNCERTAINTY

y_pred = modelo_rf_final.predict(X_test)
y_prob = modelo_rf_final.predict_proba(X_test)[:, 1]

# Extracting individual tree probabilities
predicciones_individuales = np.array([arbol.predict_proba(X_test.values)[:, 1] for arbol in modelo_rf_final.estimators_])

prob_inferior = np.percentile(predicciones_individuales, 5, axis=0)
prob_superior = np.percentile(predicciones_individuales, 95, axis=0)

print("\n=== FINAL CLASSIFICATION REPORT ===")
print(classification_report(y_test, y_pred))
print(f"ROC AUC Score: {roc_auc_score(y_test, y_prob):.4f}\n")


sns.set_theme(style="whitegrid")
fig = plt.figure(figsize=(20, 12))


# Training Class Balance
ax2 = plt.subplot(2, 3, 2)
train_counts = y_train.value_counts().sort_index()
ax2.bar(['<=50K', '>50K'], train_counts.values, color=['#c44e52', '#8172b2'])
ax2.set_title('Class Volume (Training Set)', fontweight='bold')
ax2.set_ylabel('Frequency')
for i, v in enumerate(train_counts.values):
    ax2.text(i, v + 100, f"{v:,}", ha='center')

# Confusion Matrix
ax3 = plt.subplot(2, 3, 3)
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax3, cbar=False)
ax3.set_title('Confusion Matrix', fontweight='bold')
ax3.set_xlabel('Predicted Label')
ax3.set_ylabel('Actual Label')
ax3.set_xticklabels(['<=50K', '>50K'])
ax3.set_yticklabels(['<=50K', '>50K'])

# ROC Curve
ax4 = plt.subplot(2, 3, 4)
fpr, tpr, umbrales = roc_curve(y_test, y_prob)
ax4.plot(fpr, tpr, color='darkblue', lw=2, label=f'AUC = {roc_auc_score(y_test, y_prob):.4f}')
ax4.plot([0, 1], [0, 1], color='gray', lw=2, linestyle='--')
ax4.set_xlim([0.0, 1.0])
ax4.set_ylim([0.0, 1.05])
ax4.set_xlabel('False Positive Rate (FPR)')
ax4.set_ylabel('True Positive Rate (TPR)')
ax4.set_title('Model Performance: ROC Curve', fontweight='bold')
ax4.legend(loc="lower right")

# Feature Importance
ax5 = plt.subplot(2, 3, 5)
df_imp = pd.DataFrame({'Feature': X_train.columns, 'Importance': modelo_rf_final.feature_importances_})
df_imp = df_imp.sort_values(by='Importance', ascending=False).head(8)
sns.barplot(data=df_imp, x='Importance', y='Feature', hue='Feature', palette='magma', legend=False, ax=ax5)
ax5.set_title('Predictive Power (Top 8 Features)', fontweight='bold')
ax5.set_xlabel('Mean Decrease in Impurity (Gini)')
ax5.set_ylabel('')

# Uncertainty / Confidence Intervals
ax6 = plt.subplot(2, 3, 6)
np.random.seed(42)
indices_muestra = np.random.choice(len(y_test), 50, replace=False)
indices_ordenados = indices_muestra[np.argsort(y_prob[indices_muestra])]

prob_muestra = y_prob[indices_ordenados]
err_inferior = np.clip(prob_muestra - prob_inferior[indices_ordenados], 0, None)
err_superior = np.clip(prob_superior[indices_ordenados] - prob_muestra, 0, None)

ax6.errorbar(
    range(50), prob_muestra,
    yerr=[err_inferior, err_superior],
    fmt='o', color='#8172b2', ecolor='lightgray', elinewidth=2, capsize=3, markersize=5
)
ax6.axhline(0.5, color='red', linestyle='--', alpha=0.7, label='Decision Threshold (0.5)')
ax6.set_title('Model Uncertainty (90% CI on 50 random cases)', fontweight='bold')
ax6.set_xlabel('Evaluated Cases (Sorted by Probability)')
ax6.set_ylabel('Predicted Probability (>50K)')
ax6.legend(loc="upper left")

plt.tight_layout()
plt.show()

"""## Model Explanation and Statistical Values
The model achieved a good performance, validated through Out of Sample tests:
* **ROC AUC (0.9181):** Indicates an excellent ability (91.8%) to correctly discriminate between the two income classes.
* **>50K Class Recall (0.86):** The model successfully detects 86% of all true high-income profiles, minimizing lost opportunities (False Negatives).
* **Predictive Power (Feature Importance):** Unlike a linear model with static coefficients, Random Forest measures the reduction of impurity (Gini). The `capital_gain` variable emerged as the dominant predictor, demonstrating that financial milestones have much more causal weight on final income than purely demographic characteristics like age or hours worked.
"""